package org.kungfu.generator;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

import org.kungfu.core.Constants;

import com.jfinal.kit.StrKit;

/**
 * Service 生成器
 */
public class ServiceGenerator {
	
	protected String packageTemplate =
			"package %s.%s;%n%n";
	protected String importTemplate =
			"import java.util.Date;%n%n" +
			//"import com.jfinal.plugin.activerecord.Db;%n" +
			"import com.jfinal.plugin.activerecord.Page;%n%n" +
			"import org.kungfu.core.Service;%n%n" +
			"import %s.%s.%s;%n%n";
	protected String classDefineTemplate =
		"/**%n" +
		" * Service, Generated by Robot on " + Constants.DATE_TIME + ".%n" +
		" */%n" +
		"public class %sService extends Service implements %sAPI {%n";
	
	protected String pageSampleTemplate =
			"\t@Override%n" + 
			"\tpublic Page<%s> page(int pageNumber, int pageSize) {%n" +
			"\t\treturn %s.dao.paginate(pageNumber, pageSize, \"select *\", \"from %s order by id asc\");%n" +
			"\t}%n%n";
	
	protected String pageClauseTemplate =
			"\t@Override%n" + 
			"\tpublic Page<%s> page(int pageNumber, int pageSize, String orderField, String orderDirection, String where) {%n" +
			"\t\treturn %s.dao.paginate(pageNumber, pageSize, \"select * \", String.format(\"from %s where 1=1 %s order by %s %s\", where, orderField, orderDirection));%n" +
			"\t}%n%n";
	
	protected String saveOrUpdateTemplate =
			"\t@Override%n" + 
			"\tpublic boolean saveOrUpdate(%s model, boolean isSave) {%n" +
			"\t\tboolean flag = false;%n%n" +
			"\t\tif (model.getId() == null) {%n" +
			"\t\t\t//model.setCreateTime(new Date());%n" +
			"\t\t\tflag = model.save();%n" +
			"\t\t}%n" +
			"\t\telse {%n" +
			"\t\t\t//model.setEditTime(new Date());%n" +
			"\t\t\tflag = model.update();%n" +
			"\t\t}%n" +
			"\t\treturn flag;%n" +
			"\t}%n%n";
	
	protected String findByIdTemplate =
			"\t@Override%n" + 
			"\tpublic %s findById(Object idValue) {%n" +
			"\t\treturn %s.dao.findById(idValue);%n" +
			"\t}%n%n";
	
	protected String deleteTemplate =
			"\t@Override%n" + 
			"\tpublic int delete(String ids) {%n" +
			"\t\treturn batchDelete(\"%s\", ids);%n" +
			"\t}%n%n";

	
	protected String modelPackageName;
	protected String baseModelPackageName;
	protected String modelOutputDir;
	protected boolean generateDaoInModel = true;
	
	public ServiceGenerator(String modelPackageName, String baseModelPackageName, String modelOutputDir) {
		if (StrKit.isBlank(modelPackageName))
			throw new IllegalArgumentException("modelPackageName can not be blank.");
		if (modelPackageName.contains("/") || modelPackageName.contains("\\"))
			throw new IllegalArgumentException("modelPackageName error : " + modelPackageName);
		if (StrKit.isBlank(baseModelPackageName))
			throw new IllegalArgumentException("baseModelPackageName can not be blank.");
		if (baseModelPackageName.contains("/") || baseModelPackageName.contains("\\"))
			throw new IllegalArgumentException("baseModelPackageName error : " + baseModelPackageName);
		if (StrKit.isBlank(modelOutputDir))
			throw new IllegalArgumentException("modelOutputDir can not be blank.");
		
		this.modelPackageName = modelPackageName;
		this.baseModelPackageName = baseModelPackageName;
		this.modelOutputDir = modelOutputDir;
	}
	
	public void setGenerateDaoInModel(boolean generateDaoInModel) {
		this.generateDaoInModel = generateDaoInModel;
	}
	
	public void generate(List<TableMeta> tableMetas) {
		System.out.println("Generate Service, API implement ...");
		for (TableMeta tableMeta : tableMetas)
			genModelContent(tableMeta);
		wirtToFile(tableMetas);
	}
	
	protected void genModelContent(TableMeta tableMeta) {
		StringBuilder ret = new StringBuilder();
		genPackage(tableMeta, ret);
		genImport(tableMeta, ret);
		genClassDefine(tableMeta, ret);
		genPageSampleMethod(tableMeta, ret);
		genPageClauseMethod(tableMeta, ret);
		genSaveOrUpdateMethod(tableMeta, ret);
		genFindByIdMethod(tableMeta, ret);
		genDeleteMethod(tableMeta, ret);
		ret.append(String.format("}%n"));
		tableMeta.modelContent = ret.toString();
	}
	
	protected void genPackage(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(packageTemplate, modelPackageName, tableMeta.modelName.toLowerCase().replaceAll("_", "")));
	}
	
	protected void genImport(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(importTemplate, modelPackageName, tableMeta.modelName.toLowerCase().replaceAll("_", ""), tableMeta.modelName));
	}
	
	protected void genClassDefine(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(classDefineTemplate, tableMeta.modelName, tableMeta.modelName));
	}
	
	protected void genPageSampleMethod(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(pageSampleTemplate, tableMeta.modelName, tableMeta.modelName, tableMeta.name));
	}
	
	protected void genPageClauseMethod(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(pageClauseTemplate, tableMeta.modelName, tableMeta.modelName, tableMeta.name, Constants.PLACEHOLDER, Constants.PLACEHOLDER, Constants.PLACEHOLDER));
	}
	
	protected void genSaveOrUpdateMethod(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(saveOrUpdateTemplate, StrKit.firstCharToUpperCase(tableMeta.modelName), tableMeta.modelName));
	}
	
	protected void genFindByIdMethod(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(findByIdTemplate, tableMeta.modelName, tableMeta.modelName));
	}
	
	protected void genDeleteMethod(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(deleteTemplate, tableMeta.name));
	}
	
	
	protected void wirtToFile(List<TableMeta> tableMetas) {
		try {
			for (TableMeta tableMeta : tableMetas)
				wirtToFile(tableMeta);
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
	}
	
	/**
	 * 若 model 文件存在，则不生成，以免覆盖用户手写的代码
	 */
	protected void wirtToFile(TableMeta tableMeta) throws IOException {
		File dir = new File(modelOutputDir + File.separator + tableMeta.modelName.toLowerCase().replaceAll("_", "") );
		if (!dir.exists())
			dir.mkdirs();
		
		String target = modelOutputDir + File.separator + tableMeta.modelName.toLowerCase().replaceAll("_", "") + File.separator + tableMeta.modelName + "Service.java";
		
		File file = new File(target);
		if (file.exists()) {
			return ;	// 若 Model 存在，不覆盖
		}
		
		FileWriter fw = new FileWriter(file);
		try {
			fw.write(tableMeta.modelContent);
		}
		finally {
			fw.close();
		}
	}
}


